estoque = []


#Função adicionar produtos ao estoque

def adicionar_produto():
    nome_produto = input("Digite o nome do profuto:")
    estoque.append(nome_produto)


    quant_produto = int(input("Digite a quantidade do produto"))
    estoque.append(quant_prod)

    #Função para verificar se o produto existe no estoque

    def verifica_produto():
        for produto in estoque:
            if produto[0]== estoque:
                print("O produto", produto, "esta em estoque")
            else:
                print("Não consta o produto em estoque")

def atualiza_produto():
    nova_quantidade = int(input("Digite a nova quantidade de produto:"))

    for produto [0] in estoque:
        
        

adicionar_produto()


